[CUSOLVER] Add ordering functions
JuliaGPU/CUDA.jl pull request #1198
Opened 2021-10-11 23:55 UTC by amontoison

2021-10-12 08:22 UTC, maleadt requested changes
Thanks! Couple of comments (that apply to all of these functions).

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/ordering.jl
> +    cusolverSpXcsrsymrcmHost(sparse_handle(), n, nnz(A), descA, rowsA, colsA, p)
Why do you use the host APIs here?

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/ordering.jl
> +    rowsA = A.rowPtr |> Vector{Cint}
We don't want to do this.

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/CUSOLVER.jl
> +include("ordering.jl")
Why the separate file? These aren't high-level integrations, but low-level wrappers, so belong in `sparse.jl`.

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/ordering.jl
> +        p .+= Cint(1)
Why this offset? It's up to the caller to request an appropriate indexing type and handle the results.

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/ordering.jl
> +            (numnz[] < n) && error("A has structural singulary")
`SingularException`?

2021-10-12 08:22 UTC, maleadt commented on lib/cusolver/ordering.jl
> +    descA = CUSPARSE.CuMatrixDescriptor('G', 'L', 'N', index)
Remove the CUSPARSE module prefix.

2021-10-12 08:22 UTC, maleadt commented on test/cusolver/ordering.jl
> +    p = symamd(A, 'Z')
You should also test the validity of the results.

2021-10-12 13:48 UTC, amontoison commented on test/cusolver/ordering.jl
> +    p = symamd(A, 'Z')
I will have a look at the tests of AMD.jl and METIS.jl.

2021-10-12 13:49 UTC, amontoison commented on lib/cusolver/ordering.jl
> +        p .+= Cint(1)
Ok, I removed the offset.

2021-10-12 14:02 UTC, amontoison commented on lib/cusolver/ordering.jl
> +    cusolverSpXcsrsymrcmHost(sparse_handle(), n, nnz(A), descA, rowsA, colsA, p)
- `symrcm`, `symmdq`, `symamd` and `metisnd` are used inside `cusolverRF` (https://github.com/JuliaGPU/CUDA.jl/pull/828) but no low-level wrappers are implemented.
- `zfd` should be combined in practice with `ilu0` routine (incomplete LU factorization) because the factorization is done without pivoting and if one diagonal element is zero the factorization failed.

2021-10-13 05:31 UTC, maleadt commented on lib/cusolver/ordering.jl
> +    cusolverSpXcsrsymrcmHost(sparse_handle(), n, nnz(A), descA, rowsA, colsA, p)
Ah, there aren't any device equivalents for these APIs...

2021-10-14 03:46 UTC, amontoison commented
@maleadt I take into account all your comments.

2021-10-19 02:58 UTC, amontoison commented on test/cusolver/sparse.jl
> +    p = symamd(A, 'O')
```suggestion
    p = symrcm(A, 'O')
```

2021-10-19 07:52 UTC, maleadt commented
Thanks, looks good!

2021-10-19 07:52 UTC, merged