expose sparse mv/mm algo selection
JuliaGPU/CUDA.jl pull request #1201
Opened 2021-10-14 21:10 UTC by Roger-luo

this is a simple change to expose the algorithm parameter to mv/mm level

edit: I'm not sure if we should check if the selected algo match the input, e.g some algo only work on CSR with col/row-major

2021-10-15 14:06 UTC, Roger-luo commented
I thought the current tests cover this already tho? Or we should test on other algorithms?

2021-10-15 14:52 UTC, maleadt commented
> I thought the current tests cover this already tho?

How? Didn't you introduce the `algo` keyword here?

2021-10-22 06:00 UTC, maleadt requested changes

2021-10-22 06:00 UTC, maleadt commented on test/cusparse/generic.jl
> +using Test
Don't import all these. If you want to run a single test, so `julia -L test/setup.jl test/cusparse/generic.jl`.

2021-10-22 06:00 UTC, maleadt commented on test/cusparse/generic.jl
> +Random.seed!(123)
Seed is already applied in setup.jl

2021-10-22 06:00 UTC, maleadt commented on lib/cusparse/generic.jl
> +function mv!(transa::SparseChar, alpha::Number,
Better keep the current formatting, like the rest of the file.

2021-10-22 06:00 UTC, maleadt commented on lib/cusparse/generic.jl
> +function mv!(transa::SparseChar, alpha::Number,
same.

2021-10-25 05:20 UTC, Roger-luo commented
hmm I'm a bit confused why the test is failing on CUDA 11.1, I've filter the tests to not run below CUDA 11.2, but somehow it still get executed on those versions, what would be right way of doing this?

2021-10-25 15:03 UTC, maleadt commented
`CUDA.version()` returns the driver version. You need to check against `CUSPARSE.version()` (which requires you to use the library version, so look up what the appropriate version is corresponding with CUDA toolkit 11.2 -- it's in the release notes, or you can check yourself by setting `JULIA_CUDA_VERSION=11.2`).

2021-10-25 15:31 UTC, maleadt commented on test/cusparse/generic.jl
> +if CUSPARSE.version() >= v"11.2" # lower CUDA version doesn't support these algorithms
This is wrong, and that's what I meant with having to check the version.

```
$ JULIA_CUDA_VERSION=11.2 jl -e 'using CUDA; @show CUSPARSE.version()'                                                                                       
  Downloaded artifact: CUDA
CUSPARSE.version() = v"11.4.1"
```

2021-10-26 14:12 UTC, maleadt commented
Please rebase on master to not require Windows to pass.

2022-05-09 07:31 UTC, maleadt approved these changes

2022-05-09 07:31 UTC, maleadt commented
LGTM, thanks!

2022-05-09 07:31 UTC, merged