`ldiv!` for LU Decomposition
JuliaGPU/CUDA.jl pull request #1532
Opened 2022-06-01 18:38 UTC by SBuercklin

Implements `ldiv!(::LU, ::CuVecOrMat)`, addressing Chris's comment at the end of the OP for #1193 

There are some extra type parameters on one of the two `ldiv!` methods because there's a method ambiguity with a similar method in `LinearAlgebra.jl`. If there's a better way to resolve the ambiguity with one method, I'll happy make the change

2022-06-01 21:36 UTC, maleadt reviewed
I'm not familiar with this functionality, but LGTM apart from some minor nits.

2022-06-01 21:36 UTC, maleadt commented on lib/cusolver/linalg.jl
> +    return CUSOLVER.getrs!('N', F.factors, F.ipiv, B)
No need for the CUSOLVER prefixes

2022-06-01 21:36 UTC, maleadt commented on lib/cusolver/linalg.jl
> +function LinearAlgebra.ldiv!(
Formatting is different from the rest of this file.

2022-06-01 21:36 UTC, maleadt commented on lib/cusolver/linalg.jl
> +    return CUSOLVER.getrs!('N', F.factors, F.ipiv, B)
module prefix

2022-06-01 21:36 UTC, maleadt commented on test/cusolver/dense.jl
> +
whitespace

2022-06-01 21:37 UTC, maleadt commented
Maybe @ChrisRackauckas or @kshyatt can have a quick look.

2022-06-02 14:15 UTC, SBuercklin commented
> I'm not familiar with this functionality, but LGTM apart from some minor nits.

Here's the relevant `ldiv!` method in `LinearAlgebra`: [link](https://github.com/JuliaLang/julia/blob/v1.8.0-rc1/stdlib/LinearAlgebra/src/lu.jl#L404-L405). This is essentially just a wrapper over `LAPACK.getrs!`. 

Another option is to extend `LinearAlgebra.LAPACK.getrs!` with the relevant `CUSOLVER.getrs!` call, with the original `getrs!` [here](https://github.com/JuliaLang/julia/blob/v1.8.0-rc1/stdlib/LinearAlgebra/src/lapack.jl#L1005-L1021). This should also solve problems anywhere else `getrs!` is called from `LinearAlgebra`, so I just pushed that change. It also requries only writing one method, instead of two, since there is no longer any method ambiguity on `ldiv!`

2022-06-02 15:27 UTC, ChrisRackauckas approved these changes
This looks right to me.

2022-06-02 15:29 UTC, ChrisRackauckas commented
>Another option is to extend LinearAlgebra.LAPACK.getrs! with the relevant CUSOLVER.getrs! call, with the original getrs! [here](https://github.com/JuliaLang/julia/blob/v1.8.0-rc1/stdlib/LinearAlgebra/src/lapack.jl#L1005-L1021). This should also solve problems anywhere else getrs! is called from LinearAlgebra, so I just pushed that change. It also requries only writing one method, instead of two, since there is no longer any method ambiguity on ldiv!

Generally LinearAlgebra.LAPACK is not extended. I don't know about what happens with CUDA LAPACK-like APIs though, but generally it's just the higher level LinearAlgebra APIs that are dispatched for more generic support. So I think this is fine.

2022-06-02 16:48 UTC, maleadt requested changes
> Generally LinearAlgebra.LAPACK is not extended. I don't know about what happens with CUDA LAPACK-like APIs though, but generally it's just the higher level LinearAlgebra APIs that are dispatched for more generic support. So I think this is fine.

Yup, we generally don't do this. It's true that the APIs are sometimes similar enough to make that possible, but in the general case the CUDA equivalents can't be used as a drop-in replacement (with the exception of NVBLAS being a drop-in for BLAS), so we implement the higher-level APIs. That's also more robust wrt. changes in Base Julia.

2022-06-02 17:38 UTC, SBuercklin commented
> Yup, we generally don't do this. It's true that the APIs are sometimes similar enough to make that possible, but in the general case the CUDA equivalents can't be used as a drop-in replacement (with the exception of NVBLAS being a drop-in for BLAS), so we implement the higher-level APIs. That's also more robust wrt. changes in Base Julia.

Thanks, that makes sense. I reverted the commit and fixed the changes from above

2022-06-07 08:52 UTC, maleadt approved these changes

2022-06-07 08:52 UTC, merged