Wrapper with tests for `gemmBatchedEx!`
JuliaGPU/CUDA.jl pull request #1975
Opened 2023-06-20 15:23 UTC by lpawela

This introduces a wrapper for `gemmBatchedEx!`, allowing for batched mixed precision matrix multiplication. Based on the approach used for existing `gemmEx!` and `gemm_batched!`.

2023-06-26 20:09 UTC, maleadt requested changes
Thanks! Couple of minor comments.

I'm not really fond of these interfaces, they're low-level and ugly, but we don't have anything better right now.
Do you plan to use these directly, or to extend e.g. `NNlib.batched_mul`?

2023-06-26 20:09 UTC, maleadt commented on lib/cublas/wrappers.jl
> +        throw(DimensionMismatch(""))
Can you make these (and maybe `gemmEx` while you're at it) print an actual useful error?

2023-06-26 20:09 UTC, maleadt commented on lib/cublas/wrappers.jl
> +            throw(DimensionMismatch(""))
Same here.

2023-06-26 20:09 UTC, maleadt commented on lib/cublas/wrappers.jl
> +        throw("Not implemented for CUDA versio <11")
```suggestion
        error("Not implemented for CUDA 11 and below.")
```

2023-06-26 20:09 UTC, maleadt commented on test/libraries/cublas.jl
> +                @test bC[i] ≈ h_C
Why these changes? Shouldn't the tests have failed before?

2023-06-27 09:59 UTC, lpawela commented on test/libraries/cublas.jl
> +                @test bC[i] ≈ h_C
The tests overwrote `bC` from `Vector{Matrix}` to `Matrix`.

2023-06-27 10:24 UTC, lpawela commented
I'm not planning to add it `NNlib`, I'm using these directly. I will also add here (hopefuly today) the strided version.

2023-06-29 08:03 UTC, merged