Add fast getri_strided_batch
JuliaGPU/CUDA.jl pull request #682
Opened 2021-01-27 17:21 UTC by cfranken

Add getri_strided_batch (similar to getrf_strided_batch). Allocation free inside, easier to use getrf_strided_batch and getri_strided_batch for fast batched matrix inversion now

2021-01-27 17:23 UTC, vchuravy commented
Thanks @cfranken, can you add a couple of tests https://github.com/JuliaGPU/CUDA.jl/blob/master/test/cublas.jl

2021-01-27 19:34 UTC, maleadt requested changes

2021-01-27 19:34 UTC, maleadt commented on lib/cublas/wrappers.jl
> +            CUBLAS.$fname(CUBLAS.handle(), n, Aptrs, lda, pivotArray, Cptrs, ldc, info, batchSize)
This is inside the CUBLAS module already, so you shouldn't need these prefixes.

2021-01-27 19:34 UTC, maleadt commented on lib/cublas/wrappers.jl
> +            Aptrs = CUBLAS.unsafe_batch(A)
Same here

2021-01-27 20:41 UTC, cfranken reviewed
Removed CUBLAS prefixes and some commented lines

2021-01-27 20:41 UTC, cfranken commented on lib/cublas/wrappers.jl
> +            CUBLAS.$fname(CUBLAS.handle(), n, Aptrs, lda, pivotArray, Cptrs, ldc, info, batchSize)
not sure I fully understand. Only a 
`getri_batched(A::Vector{<:CuMatrix{$elty}},pivotArray::CuMatrix{Cint})`
function existed, which allocated a new `C`. Or did I misunderstand (sorry, my first PR for Julia!)?

2021-01-28 10:06 UTC, maleadt reviewed
Thanks! Some minor nits.

2021-01-28 10:06 UTC, maleadt commented on test/cublas.jl
> +            A = rand(elty,m,m,10);
No need for these changes.

2021-01-28 10:06 UTC, maleadt commented on test/cublas.jl
> +            d_A = CuArray(A);
Same.

2021-01-28 16:01 UTC, cfranken commented on test/cublas.jl
> +            d_A = CuArray(A);
done

2021-01-28 16:01 UTC, cfranken commented on test/cublas.jl
> +            A = rand(elty,m,m,10);
done

2021-01-28 16:45 UTC, maleadt approved these changes

2021-02-02 13:46 UTC, merged